# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'konventor_len.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(880, 340)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 858, 57))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 100, 489, 231))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_2.setItemText(0, _translate("Form", "Метр"))
        self.comboBox_2.setItemText(1, _translate("Form", "Километр"))
        self.comboBox_2.setItemText(2, _translate("Form", "Дециметр"))
        self.comboBox_2.setItemText(3, _translate("Form", "Сантиметр"))
        self.comboBox_2.setItemText(4, _translate("Form", "Миллиметр"))
        self.comboBox_2.setItemText(5, _translate("Form", "Микрометр"))
        self.comboBox_2.setItemText(6, _translate("Form", "Нанометр"))
        self.comboBox_2.setItemText(7, _translate("Form", "Пикометр"))
        self.comboBox_2.setItemText(8, _translate("Form", "Фемтометр"))
        self.comboBox_2.setItemText(9, _translate("Form", "Лига (Лье)"))
        self.comboBox_2.setItemText(10, _translate("Form", "Миля"))
        self.comboBox_2.setItemText(11, _translate("Form", "Фурлонг"))
        self.comboBox_2.setItemText(12, _translate("Form", "Чейн"))
        self.comboBox_2.setItemText(13, _translate("Form", "Род"))
        self.comboBox_2.setItemText(14, _translate("Form", "Ярд"))
        self.comboBox_2.setItemText(15, _translate("Form", "Инспекционный фут"))
        self.comboBox_2.setItemText(16, _translate("Form", "Фут"))
        self.comboBox_2.setItemText(17, _translate("Form", "Линк"))
        self.comboBox_2.setItemText(18, _translate("Form", "Хэнд"))
        self.comboBox_2.setItemText(19, _translate("Form", "Дюйм"))
        self.comboBox_2.setItemText(20, _translate("Form", "Линия большая"))
        self.comboBox_2.setItemText(21, _translate("Form", "Линия Малая"))
        self.comboBox_2.setItemText(22, _translate("Form", "Мил"))
        self.comboBox_2.setItemText(23, _translate("Form", "Мо"))
        self.comboBox_2.setItemText(24, _translate("Form", "Рин"))
        self.comboBox_2.setItemText(25, _translate("Form", "Бу"))
        self.comboBox_2.setItemText(26, _translate("Form", "Сун"))
        self.comboBox_2.setItemText(27, _translate("Form", "Сяку"))
        self.comboBox_2.setItemText(28, _translate("Form", "Кэн"))
        self.comboBox_2.setItemText(29, _translate("Form", "Хиро"))
        self.comboBox_2.setItemText(30, _translate("Form", "Дзё"))
        self.comboBox_2.setItemText(31, _translate("Form", "Тё"))
        self.comboBox_2.setItemText(32, _translate("Form", "Ри"))
        self.comboBox_2.setItemText(33, _translate("Form", "Палайста"))
        self.comboBox_2.setItemText(34, _translate("Form", "Плетр"))
        self.comboBox_2.setItemText(35, _translate("Form", "Миля"))
        self.comboBox_2.setItemText(36, _translate("Form", "Стадий"))
        self.comboBox_2.setItemText(37, _translate("Form", "Плетр"))
        self.comboBox_2.setItemText(38, _translate("Form", "Амма"))
        self.comboBox_2.setItemText(39, _translate("Form", "Акена (декапод)"))
        self.comboBox_2.setItemText(40, _translate("Form", "Оргия (гексапод)"))
        self.comboBox_2.setItemText(41, _translate("Form", "Бема (шаг)"))
        self.comboBox_2.setItemText(42, _translate("Form", "Пехис (локоть) греческий"))
        self.comboBox_2.setItemText(43, _translate("Form", "Пехис (локоть) короткий"))
        self.comboBox_2.setItemText(44, _translate("Form", "Пус (фут)"))
        self.comboBox_2.setItemText(45, _translate("Form", "Спитам"))
        self.comboBox_2.setItemText(46, _translate("Form", "Дихас"))
        self.comboBox_2.setItemText(47, _translate("Form", "Палестра (ладонь) "))
        self.comboBox_2.setItemText(48, _translate("Form", "Кондиль "))
        self.comboBox_2.setItemText(49, _translate("Form", "Дактиль (палец)"))
        self.comboBox_2.setItemText(50, _translate("Form", "Стадий олимпийский"))
        self.comboBox_2.setItemText(51, _translate("Form", "Стадий аттический"))
        self.comboBox_2.setItemText(52, _translate("Form", "Стадий птолемеевский"))
        self.comboBox_2.setItemText(53, _translate("Form", "Морская миля"))
        self.comboBox_2.setItemText(54, _translate("Form", "Кабельтов"))
        self.comboBox_2.setItemText(55, _translate("Form", "Морская сажень"))
        self.comboBox_2.setItemText(56, _translate("Form", "Радиус Луны"))
        self.comboBox_2.setItemText(57, _translate("Form", "Радиус Земли"))
        self.comboBox_2.setItemText(58, _translate("Form", "Радиус Юпитера"))
        self.comboBox_2.setItemText(59, _translate("Form", "Радиус Солнца"))
        self.comboBox_2.setItemText(60, _translate("Form", "Световой месяц"))
        self.comboBox_2.setItemText(61, _translate("Form", "Световая минута"))
        self.comboBox_2.setItemText(62, _translate("Form", "Астрономическая единица"))
        self.comboBox_2.setItemText(63, _translate("Form", "Световой час"))
        self.comboBox_2.setItemText(64, _translate("Form", "Световые сутки"))
        self.comboBox_2.setItemText(65, _translate("Form", "Световая неделя"))
        self.comboBox_2.setItemText(66, _translate("Form", "Световой год"))
        self.comboBox_2.setItemText(67, _translate("Form", "Парсек"))
        self.comboBox_2.setItemText(68, _translate("Form", "Сириометр"))
        self.comboBox_2.setItemText(69, _translate("Form", "Планковская длина"))
        self.comboBox_2.setItemText(70, _translate("Form", "Ферми"))
        self.comboBox_2.setItemText(71, _translate("Form", "Класический радиус электрона"))
        self.comboBox_2.setItemText(72, _translate("Form", "X-еденица"))
        self.comboBox_2.setItemText(73, _translate("Form", "Комптоновская длина волны электрона"))
        self.comboBox_2.setItemText(74, _translate("Form", "Боровский радиус"))
        self.comboBox_2.setItemText(75, _translate("Form", "Ангстрем"))
        self.comboBox_2.setItemText(76, _translate("Form", "Юнит"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "="))
        self.comboBox_3.setItemText(0, _translate("Form", "Метр"))
        self.comboBox_3.setItemText(1, _translate("Form", "Километр"))
        self.comboBox_3.setItemText(2, _translate("Form", "Дециметр"))
        self.comboBox_3.setItemText(3, _translate("Form", "Сантиметр"))
        self.comboBox_3.setItemText(4, _translate("Form", "Миллиметр"))
        self.comboBox_3.setItemText(5, _translate("Form", "Микрометр"))
        self.comboBox_3.setItemText(6, _translate("Form", "Нанометр"))
        self.comboBox_3.setItemText(7, _translate("Form", "Пикометр"))
        self.comboBox_3.setItemText(8, _translate("Form", "Фемтометр"))
        self.comboBox_3.setItemText(9, _translate("Form", "Лига (Лье)"))
        self.comboBox_3.setItemText(10, _translate("Form", "Миля"))
        self.comboBox_3.setItemText(11, _translate("Form", "Фурлонг"))
        self.comboBox_3.setItemText(12, _translate("Form", "Чейн"))
        self.comboBox_3.setItemText(13, _translate("Form", "Род"))
        self.comboBox_3.setItemText(14, _translate("Form", "Ярд"))
        self.comboBox_3.setItemText(15, _translate("Form", "Инспекционный фут"))
        self.comboBox_3.setItemText(16, _translate("Form", "Фут"))
        self.comboBox_3.setItemText(17, _translate("Form", "Линк"))
        self.comboBox_3.setItemText(18, _translate("Form", "Хэнд"))
        self.comboBox_3.setItemText(19, _translate("Form", "Дюйм"))
        self.comboBox_3.setItemText(20, _translate("Form", "Линия большая"))
        self.comboBox_3.setItemText(21, _translate("Form", "Линия Малая"))
        self.comboBox_3.setItemText(22, _translate("Form", "Мил"))
        self.comboBox_3.setItemText(23, _translate("Form", "Мо"))
        self.comboBox_3.setItemText(24, _translate("Form", "Рин"))
        self.comboBox_3.setItemText(25, _translate("Form", "Бу"))
        self.comboBox_3.setItemText(26, _translate("Form", "Сун"))
        self.comboBox_3.setItemText(27, _translate("Form", "Сяку"))
        self.comboBox_3.setItemText(28, _translate("Form", "Кэн"))
        self.comboBox_3.setItemText(29, _translate("Form", "Хиро"))
        self.comboBox_3.setItemText(30, _translate("Form", "Дзё"))
        self.comboBox_3.setItemText(31, _translate("Form", "Тё"))
        self.comboBox_3.setItemText(32, _translate("Form", "Ри"))
        self.comboBox_3.setItemText(33, _translate("Form", "Палайста"))
        self.comboBox_3.setItemText(34, _translate("Form", "Плетр"))
        self.comboBox_3.setItemText(35, _translate("Form", "Миля"))
        self.comboBox_3.setItemText(36, _translate("Form", "Стадий"))
        self.comboBox_3.setItemText(37, _translate("Form", "Плетр"))
        self.comboBox_3.setItemText(38, _translate("Form", "Амма"))
        self.comboBox_3.setItemText(39, _translate("Form", "Акена (декапод)"))
        self.comboBox_3.setItemText(40, _translate("Form", "Оргия (гексапод)"))
        self.comboBox_3.setItemText(41, _translate("Form", "Бема (шаг)"))
        self.comboBox_3.setItemText(42, _translate("Form", "Пехис (локоть) греческий"))
        self.comboBox_3.setItemText(43, _translate("Form", "Пехис (локоть) короткий"))
        self.comboBox_3.setItemText(44, _translate("Form", "Пус (фут)"))
        self.comboBox_3.setItemText(45, _translate("Form", "Спитам"))
        self.comboBox_3.setItemText(46, _translate("Form", "Дихас"))
        self.comboBox_3.setItemText(47, _translate("Form", "Палестра (ладонь) "))
        self.comboBox_3.setItemText(48, _translate("Form", "Кондиль "))
        self.comboBox_3.setItemText(49, _translate("Form", "Дактиль (палец)"))
        self.comboBox_3.setItemText(50, _translate("Form", "Стадий олимпийский"))
        self.comboBox_3.setItemText(51, _translate("Form", "Стадий аттический"))
        self.comboBox_3.setItemText(52, _translate("Form", "Стадий птолемеевский"))
        self.comboBox_3.setItemText(53, _translate("Form", "Морская миля"))
        self.comboBox_3.setItemText(54, _translate("Form", "Кабельтов"))
        self.comboBox_3.setItemText(55, _translate("Form", "Морская сажень"))
        self.comboBox_3.setItemText(56, _translate("Form", "Радиус Луны"))
        self.comboBox_3.setItemText(57, _translate("Form", "Радиус Земли"))
        self.comboBox_3.setItemText(58, _translate("Form", "Радиус Юпитера"))
        self.comboBox_3.setItemText(59, _translate("Form", "Радиус Солнца"))
        self.comboBox_3.setItemText(60, _translate("Form", "Световой месяц"))
        self.comboBox_3.setItemText(61, _translate("Form", "Световая минута"))
        self.comboBox_3.setItemText(62, _translate("Form", "Астрономическая единица"))
        self.comboBox_3.setItemText(63, _translate("Form", "Световой час"))
        self.comboBox_3.setItemText(64, _translate("Form", "Световые сутки"))
        self.comboBox_3.setItemText(65, _translate("Form", "Световая неделя"))
        self.comboBox_3.setItemText(66, _translate("Form", "Световой год"))
        self.comboBox_3.setItemText(67, _translate("Form", "Парсек"))
        self.comboBox_3.setItemText(68, _translate("Form", "Сириометр"))
        self.comboBox_3.setItemText(69, _translate("Form", "Планковская длина"))
        self.comboBox_3.setItemText(70, _translate("Form", "Ферми"))
        self.comboBox_3.setItemText(71, _translate("Form", "Класический радиус электрона"))
        self.comboBox_3.setItemText(72, _translate("Form", "X-еденица"))
        self.comboBox_3.setItemText(73, _translate("Form", "Комптоновская длина волны электрона"))
        self.comboBox_3.setItemText(74, _translate("Form", "Боровский радиус"))
        self.comboBox_3.setItemText(75, _translate("Form", "Ангстрем"))
        self.comboBox_3.setItemText(76, _translate("Form", "Юнит"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.comboBox_4.setItemText(0, _translate("Form", "Метр"))
        self.comboBox_4.setItemText(1, _translate("Form", "Километр"))
        self.comboBox_4.setItemText(2, _translate("Form", "Дециметр"))
        self.comboBox_4.setItemText(3, _translate("Form", "Сантиметр"))
        self.comboBox_4.setItemText(4, _translate("Form", "Миллиметр"))
        self.comboBox_4.setItemText(5, _translate("Form", "Микрометр"))
        self.comboBox_4.setItemText(6, _translate("Form", "Нанометр"))
        self.comboBox_4.setItemText(7, _translate("Form", "Пикометр"))
        self.comboBox_4.setItemText(8, _translate("Form", "Фемтометр"))
        self.comboBox_4.setItemText(9, _translate("Form", "Лига (Лье)"))
        self.comboBox_4.setItemText(10, _translate("Form", "Миля"))
        self.comboBox_4.setItemText(11, _translate("Form", "Фурлонг"))
        self.comboBox_4.setItemText(12, _translate("Form", "Чейн"))
        self.comboBox_4.setItemText(13, _translate("Form", "Род"))
        self.comboBox_4.setItemText(14, _translate("Form", "Ярд"))
        self.comboBox_4.setItemText(15, _translate("Form", "Инспекционный фут"))
        self.comboBox_4.setItemText(16, _translate("Form", "Фут"))
        self.comboBox_4.setItemText(17, _translate("Form", "Линк"))
        self.comboBox_4.setItemText(18, _translate("Form", "Хэнд"))
        self.comboBox_4.setItemText(19, _translate("Form", "Дюйм"))
        self.comboBox_4.setItemText(20, _translate("Form", "Линия большая"))
        self.comboBox_4.setItemText(21, _translate("Form", "Линия Малая"))
        self.comboBox_4.setItemText(22, _translate("Form", "Мил"))
        self.comboBox_4.setItemText(23, _translate("Form", "Мо"))
        self.comboBox_4.setItemText(24, _translate("Form", "Рин"))
        self.comboBox_4.setItemText(25, _translate("Form", "Бу"))
        self.comboBox_4.setItemText(26, _translate("Form", "Сун"))
        self.comboBox_4.setItemText(27, _translate("Form", "Сяку"))
        self.comboBox_4.setItemText(28, _translate("Form", "Кэн"))
        self.comboBox_4.setItemText(29, _translate("Form", "Хиро"))
        self.comboBox_4.setItemText(30, _translate("Form", "Дзё"))
        self.comboBox_4.setItemText(31, _translate("Form", "Тё"))
        self.comboBox_4.setItemText(32, _translate("Form", "Ри"))
        self.comboBox_4.setItemText(33, _translate("Form", "Палайста"))
        self.comboBox_4.setItemText(34, _translate("Form", "Плетр"))
        self.comboBox_4.setItemText(35, _translate("Form", "Миля"))
        self.comboBox_4.setItemText(36, _translate("Form", "Стадий"))
        self.comboBox_4.setItemText(37, _translate("Form", "Плетр"))
        self.comboBox_4.setItemText(38, _translate("Form", "Амма"))
        self.comboBox_4.setItemText(39, _translate("Form", "Акена (декапод)"))
        self.comboBox_4.setItemText(40, _translate("Form", "Оргия (гексапод)"))
        self.comboBox_4.setItemText(41, _translate("Form", "Бема (шаг)"))
        self.comboBox_4.setItemText(42, _translate("Form", "Пехис (локоть) греческий"))
        self.comboBox_4.setItemText(43, _translate("Form", "Пехис (локоть) короткий"))
        self.comboBox_4.setItemText(44, _translate("Form", "Пус (фут)"))
        self.comboBox_4.setItemText(45, _translate("Form", "Спитам"))
        self.comboBox_4.setItemText(46, _translate("Form", "Дихас"))
        self.comboBox_4.setItemText(47, _translate("Form", "Палестра (ладонь) "))
        self.comboBox_4.setItemText(48, _translate("Form", "Кондиль "))
        self.comboBox_4.setItemText(49, _translate("Form", "Дактиль (палец)"))
        self.comboBox_4.setItemText(50, _translate("Form", "Стадий олимпийский"))
        self.comboBox_4.setItemText(51, _translate("Form", "Стадий аттический"))
        self.comboBox_4.setItemText(52, _translate("Form", "Стадий птолемеевский"))
        self.comboBox_4.setItemText(53, _translate("Form", "Морская миля"))
        self.comboBox_4.setItemText(54, _translate("Form", "Кабельтов"))
        self.comboBox_4.setItemText(55, _translate("Form", "Морская сажень"))
        self.comboBox_4.setItemText(56, _translate("Form", "Радиус Луны"))
        self.comboBox_4.setItemText(57, _translate("Form", "Радиус Земли"))
        self.comboBox_4.setItemText(58, _translate("Form", "Радиус Юпитера"))
        self.comboBox_4.setItemText(59, _translate("Form", "Радиус Солнца"))
        self.comboBox_4.setItemText(60, _translate("Form", "Световой месяц"))
        self.comboBox_4.setItemText(61, _translate("Form", "Световая минута"))
        self.comboBox_4.setItemText(62, _translate("Form", "Астрономическая единица"))
        self.comboBox_4.setItemText(63, _translate("Form", "Световой час"))
        self.comboBox_4.setItemText(64, _translate("Form", "Световые сутки"))
        self.comboBox_4.setItemText(65, _translate("Form", "Световая неделя"))
        self.comboBox_4.setItemText(66, _translate("Form", "Световой год"))
        self.comboBox_4.setItemText(67, _translate("Form", "Парсек"))
        self.comboBox_4.setItemText(68, _translate("Form", "Сириометр"))
        self.comboBox_4.setItemText(69, _translate("Form", "Планковская длина"))
        self.comboBox_4.setItemText(70, _translate("Form", "Ферми"))
        self.comboBox_4.setItemText(71, _translate("Form", "Класический радиус электрона"))
        self.comboBox_4.setItemText(72, _translate("Form", "X-еденица"))
        self.comboBox_4.setItemText(73, _translate("Form", "Комптоновская длина волны электрона"))
        self.comboBox_4.setItemText(74, _translate("Form", "Боровский радиус"))
        self.comboBox_4.setItemText(75, _translate("Form", "Ангстрем"))
        self.comboBox_4.setItemText(76, _translate("Form", "Юнит"))
        self.pushButton_2.setText(_translate("Form", "Узнать определение"))

