# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MC.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(830, 340)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 809, 57))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 100, 489, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_2.setItemText(0, _translate("Form", "Килограмм"))
        self.comboBox_2.setItemText(1, _translate("Form", "Грамм"))
        self.comboBox_2.setItemText(2, _translate("Form", "Тонна"))
        self.comboBox_2.setItemText(3, _translate("Form", "Центнер"))
        self.comboBox_2.setItemText(4, _translate("Form", "Карат"))
        self.comboBox_2.setItemText(5, _translate("Form", "Атомная еденица массы"))
        self.comboBox_2.setItemText(6, _translate("Form", "Солнечная масса"))
        self.comboBox_2.setItemText(7, _translate("Form", "Электронвольт"))
        self.comboBox_2.setItemText(8, _translate("Form", "Масса протона"))
        self.comboBox_2.setItemText(9, _translate("Form", "Планковская еденица массы"))
        self.comboBox_2.setItemText(10, _translate("Form", "Стоун"))
        self.comboBox_2.setItemText(11, _translate("Form", "Фунт (Американский)"))
        self.comboBox_2.setItemText(12, _translate("Form", "Унция"))
        self.comboBox_2.setItemText(13, _translate("Form", "Драхма (единица измерения массы, США)"))
        self.comboBox_2.setItemText(14, _translate("Form", "Гран (Американский)"))
        self.comboBox_2.setItemText(15, _translate("Form", "Короткая тонна"))
        self.comboBox_2.setItemText(16, _translate("Form", "Короткий хандредвейт"))
        self.comboBox_2.setItemText(17, _translate("Form", "Тройский фунт"))
        self.comboBox_2.setItemText(18, _translate("Form", "Тройская унция"))
        self.comboBox_2.setItemText(19, _translate("Form", "Драхма (единица измерения массы, Великобритания)"))
        self.comboBox_2.setItemText(20, _translate("Form", "Скрупул"))
        self.comboBox_2.setItemText(21, _translate("Form", "Гран (Британский)"))
        self.comboBox_2.setItemText(22, _translate("Form", "Берковец"))
        self.comboBox_2.setItemText(23, _translate("Form", "Пуд"))
        self.comboBox_2.setItemText(24, _translate("Form", "Фунт (Русский)"))
        self.comboBox_2.setItemText(25, _translate("Form", "Лот"))
        self.comboBox_2.setItemText(26, _translate("Form", "Золотник"))
        self.comboBox_2.setItemText(27, _translate("Form", "Доля"))
        self.comboBox_2.setItemText(28, _translate("Form", "Аса"))
        self.comboBox_2.setItemText(29, _translate("Form", "Английская тонна"))
        self.comboBox_2.setItemText(30, _translate("Form", "Марка"))
        self.comboBox_2.setItemText(31, _translate("Form", "Тод"))
        self.comboBox_2.setItemText(32, _translate("Form", "Феркин"))
        self.comboBox_2.setItemText(33, _translate("Form", "Хандредвейт"))
        self.comboBox_2.setItemText(34, _translate("Form", "Хогсхед"))
        self.comboBox_2.setItemText(35, _translate("Form", "Дарейк"))
        self.comboBox_2.setItemText(36, _translate("Form", "Драхма (Античная)"))
        self.comboBox_2.setItemText(37, _translate("Form", "Мина"))
        self.comboBox_2.setItemText(38, _translate("Form", "Обол"))
        self.comboBox_2.setItemText(39, _translate("Form", "Талант"))
        self.comboBox_2.setItemText(40, _translate("Form", "Халк"))
        self.comboBox_2.setItemText(41, _translate("Form", "Шекель"))
        self.comboBox_2.setItemText(42, _translate("Form", "Кэтти"))
        self.comboBox_2.setItemText(43, _translate("Form", "Манэ"))
        self.comboBox_2.setItemText(44, _translate("Form", "Арбуза"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "="))
        self.comboBox_3.setItemText(0, _translate("Form", "Килограмм"))
        self.comboBox_3.setItemText(1, _translate("Form", "Грамм"))
        self.comboBox_3.setItemText(2, _translate("Form", "Тонна"))
        self.comboBox_3.setItemText(3, _translate("Form", "Центнер"))
        self.comboBox_3.setItemText(4, _translate("Form", "Карат"))
        self.comboBox_3.setItemText(5, _translate("Form", "Атомная еденица массы"))
        self.comboBox_3.setItemText(6, _translate("Form", "Солнечная масса"))
        self.comboBox_3.setItemText(7, _translate("Form", "Электронвольт"))
        self.comboBox_3.setItemText(8, _translate("Form", "Масса протона"))
        self.comboBox_3.setItemText(9, _translate("Form", "Планковская еденица массы"))
        self.comboBox_3.setItemText(10, _translate("Form", "Стоун"))
        self.comboBox_3.setItemText(11, _translate("Form", "Фунт (Американский)"))
        self.comboBox_3.setItemText(12, _translate("Form", "Унция"))
        self.comboBox_3.setItemText(13, _translate("Form", "Драхма (единица измерения массы, США)"))
        self.comboBox_3.setItemText(14, _translate("Form", "Гран (Американский)"))
        self.comboBox_3.setItemText(15, _translate("Form", "Короткая тонна"))
        self.comboBox_3.setItemText(16, _translate("Form", "Короткий хандредвейт"))
        self.comboBox_3.setItemText(17, _translate("Form", "Тройский фунт"))
        self.comboBox_3.setItemText(18, _translate("Form", "Тройская унция"))
        self.comboBox_3.setItemText(19, _translate("Form", "Драхма (единица измерения массы, Великобритания)"))
        self.comboBox_3.setItemText(20, _translate("Form", "Скрупул"))
        self.comboBox_3.setItemText(21, _translate("Form", "Гран (Британский)"))
        self.comboBox_3.setItemText(22, _translate("Form", "Берковец"))
        self.comboBox_3.setItemText(23, _translate("Form", "Пуд"))
        self.comboBox_3.setItemText(24, _translate("Form", "Фунт (Русский)"))
        self.comboBox_3.setItemText(25, _translate("Form", "Лот"))
        self.comboBox_3.setItemText(26, _translate("Form", "Золотник"))
        self.comboBox_3.setItemText(27, _translate("Form", "Доля"))
        self.comboBox_3.setItemText(28, _translate("Form", "Аса"))
        self.comboBox_3.setItemText(29, _translate("Form", "Английская тонна"))
        self.comboBox_3.setItemText(30, _translate("Form", "Марка"))
        self.comboBox_3.setItemText(31, _translate("Form", "Тод"))
        self.comboBox_3.setItemText(32, _translate("Form", "Феркин"))
        self.comboBox_3.setItemText(33, _translate("Form", "Хандредвейт"))
        self.comboBox_3.setItemText(34, _translate("Form", "Хогсхед"))
        self.comboBox_3.setItemText(35, _translate("Form", "Дарейк"))
        self.comboBox_3.setItemText(36, _translate("Form", "Драхма (Античная)"))
        self.comboBox_3.setItemText(37, _translate("Form", "Мина"))
        self.comboBox_3.setItemText(38, _translate("Form", "Обол"))
        self.comboBox_3.setItemText(39, _translate("Form", "Талант"))
        self.comboBox_3.setItemText(40, _translate("Form", "Халк"))
        self.comboBox_3.setItemText(41, _translate("Form", "Шекель"))
        self.comboBox_3.setItemText(42, _translate("Form", "Кэтти"))
        self.comboBox_3.setItemText(43, _translate("Form", "Манэ"))
        self.comboBox_3.setItemText(44, _translate("Form", "Арбуза"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.comboBox_4.setItemText(0, _translate("Form", "Килограмм"))
        self.comboBox_4.setItemText(1, _translate("Form", "Грамм"))
        self.comboBox_4.setItemText(2, _translate("Form", "Тонна"))
        self.comboBox_4.setItemText(3, _translate("Form", "Центнер"))
        self.comboBox_4.setItemText(4, _translate("Form", "Карат"))
        self.comboBox_4.setItemText(5, _translate("Form", "Атомная еденица массы"))
        self.comboBox_4.setItemText(6, _translate("Form", "Солнечная масса"))
        self.comboBox_4.setItemText(7, _translate("Form", "Электронвольт"))
        self.comboBox_4.setItemText(8, _translate("Form", "Масса протона"))
        self.comboBox_4.setItemText(9, _translate("Form", "Планковская еденица массы"))
        self.comboBox_4.setItemText(10, _translate("Form", "Стоун"))
        self.comboBox_4.setItemText(11, _translate("Form", "Фунт (Американский)"))
        self.comboBox_4.setItemText(12, _translate("Form", "Унция"))
        self.comboBox_4.setItemText(13, _translate("Form", "Драхма (единица измерения массы, США)"))
        self.comboBox_4.setItemText(14, _translate("Form", "Гран (Американский)"))
        self.comboBox_4.setItemText(15, _translate("Form", "Короткая тонна"))
        self.comboBox_4.setItemText(16, _translate("Form", "Короткий хандредвейт"))
        self.comboBox_4.setItemText(17, _translate("Form", "Тройский фунт"))
        self.comboBox_4.setItemText(18, _translate("Form", "Тройская унция"))
        self.comboBox_4.setItemText(19, _translate("Form", "Драхма (единица измерения массы, Великобритания)"))
        self.comboBox_4.setItemText(20, _translate("Form", "Скрупул"))
        self.comboBox_4.setItemText(21, _translate("Form", "Гран (Британский)"))
        self.comboBox_4.setItemText(22, _translate("Form", "Берковец"))
        self.comboBox_4.setItemText(23, _translate("Form", "Пуд"))
        self.comboBox_4.setItemText(24, _translate("Form", "Фунт (Русский)"))
        self.comboBox_4.setItemText(25, _translate("Form", "Лот"))
        self.comboBox_4.setItemText(26, _translate("Form", "Золотник"))
        self.comboBox_4.setItemText(27, _translate("Form", "Доля"))
        self.comboBox_4.setItemText(28, _translate("Form", "Аса"))
        self.comboBox_4.setItemText(29, _translate("Form", "Английская тонна"))
        self.comboBox_4.setItemText(30, _translate("Form", "Марка"))
        self.comboBox_4.setItemText(31, _translate("Form", "Тод"))
        self.comboBox_4.setItemText(32, _translate("Form", "Феркин"))
        self.comboBox_4.setItemText(33, _translate("Form", "Хандредвейт"))
        self.comboBox_4.setItemText(34, _translate("Form", "Хогсхед"))
        self.comboBox_4.setItemText(35, _translate("Form", "Дарейк"))
        self.comboBox_4.setItemText(36, _translate("Form", "Драхма (Античная)"))
        self.comboBox_4.setItemText(37, _translate("Form", "Мина"))
        self.comboBox_4.setItemText(38, _translate("Form", "Обол"))
        self.comboBox_4.setItemText(39, _translate("Form", "Талант"))
        self.comboBox_4.setItemText(40, _translate("Form", "Халк"))
        self.comboBox_4.setItemText(41, _translate("Form", "Шекель"))
        self.comboBox_4.setItemText(42, _translate("Form", "Кэтти"))
        self.comboBox_4.setItemText(43, _translate("Form", "Манэ"))
        self.comboBox_4.setItemText(44, _translate("Form", "Арбуза"))
        self.pushButton_2.setText(_translate("Form", "Узнать определение"))

